# Generated by Django 4.2.5 on 2023-09-20 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FrancoSolanoApp", "0002_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="sector",
        ),
    ]
