# Generated by Django 4.2.5 on 2023-09-20 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FrancoSolanoApp", "0003_delete_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendedor",
            name="sector",
        ),
    ]
